projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-southeast-2
        apiId: #When the IAC is deployed replace this with the API ID, then run `codegen` to generate the types
        frontend: javascript
        framework: none
        maxDepth: 2
extensions:
  amplify:
    version: 3
