name: Publish
on:
  push:
    branches:
      - main
      - develop 

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
  
  pre-release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        if: github.ref == 'refs/heads/develop'
        run: npx jsr publish --pre-release
